# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.25.10.164:3306/social
    username: social
    password: 5AKHjdPRGWnYeFLK
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  #redis
  redis:
    port: 6379
    host: 172.19.0.2
    database: 0
